global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: https://prometheus-prod-58-prod-eu-central-0.grafana.net/api/prom/push
    basic_auth:
      username: 2830363
      password: glc_eyJvIjoiMTYwMjk3MiIsIm4iOiJzdGFjay0xNDUzMDY1LWFsbG95LWVhcnRocXVha2UiLCJrIjoiNjQ1ckdhN2wwb3p2NU93OTIxb0V4dmQ4IiwibSI6eyJyIjoicHJvZC1ldS1jZW50cmFsLTAifX0=

scrape_configs:
  # Scrape do próprio Prometheus (só pra debug)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Earthquakes API no Heroku
  - job_name: "earthquakes_api"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["earthquake-ce5c9a0f9ec7.herokuapp.com"]
